name: Build/deploy docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Build docs"
    runs-on: self-hosted
    container:
      image: docker://firedrakeproject/firedrake-docdeps:2025-01
    steps:
      - name: Fix permissions
        run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
      - name: Install
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install -e .
          python -m pip install sphinx
          python -m pip install sphinxcontrib-bibtex
      - name: Check documentation links
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd docs
          make linkcheck
      - name: Build docs
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd docs
          make html
          make latex
          make latexpdf
      - name: Copy manual to HTML tree
        run: |
          cd docs
          cp build/latex/Irksome.pdf build/html/_static/manual.pdf
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: /__w/Irksome/Irksome/docs/build/html
          retention-days: 1
      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./docs/build/html
          keep_history: false
          allow_empty_commit: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
